appuio/nagios-plugins-openshift

- check_openshift_pv_avail
Persistent volumes provisioned dynamically are marked with an annotation
("pv.kubernetes.io/provisioned-by"). These volumes aren't created
statically, hence it's perfectly valid to skip them in monitoring.
> pv_avail: Ignore dynamically-provisioned PVs

- debian/changelog
Recent changes need to be deployed, hence a new version is necessary.
> Update changelog for version 0.11.10

- check_openshift_pod_count
- debian/changelog
When the eviction manager decides to move a pod to another node due to
resource pressure (i.e. memory) the pod ends up with a status object
without the "conditions" key. Handle this case in
"check_openshift_pod_count".
> Handle pods without conditions in status object

- check_openshift_node_fluentd
- debian/changelog
- redhat/nagios-plugins-openshift.spec
The "check_openshift_node_fluentd" script didn't look at all nodes, but
only those marked schedulable. Normally master nodes are not schedulable
and hence monitoring wouldn't notice Fluentd not running on those.
> Check for Fluentd on all nodes

- check_openshift_pvc_phase
- debian/changelog
- redhat/nagios-plugins-openshift.spec
Amend the "check_openshift_pvc_phase" script to show requested size,
volume name and bound capacity for pending and lost claims. These bits
can be useful in resolving issues and save the operator from having to
look them up on the cluster.
> Show additional info for pending and lost volume claims

- debian/changelog
- new-app-and-wait
- redhat/nagios-plugins-openshift.spec
- vshn_npo/oc_client.py
The upstream code for "oc new-app" can leave a clone of the application
source behind in a temporary directory. Explicitly specify a temporary
directory which is then removed by the wrapper code to prevent code from
being left behind.
> Specify temporary directory for "oc new-app"

- check_openshift_project_pod_phase
- debian/changelog
- openshift.conf
- redhat/nagios-plugins-openshift.spec
The newly added "check_openshift_project_pod_phase" script computes
statistics on the number of pods in each possible phase (pending,
running, etc.), globally across the cluster as well as per project. For
each metric a warning and critical limit can be set.
> Add script to observe pod phase of all pods

- debian/changelog
- openshift.conf
- redhat/nagios-plugins-openshift.spec
The "check_openshift_project_pod_phase" plugin can also evaluate the
total number of pods per project. Expose that as a dedicated Icinga2
variable.
> Expose total pod count as Icinga2 variable

- debian/changelog
- openshift.conf
- redhat/nagios-plugins-openshift.spec
The arguments for the "openshift_node_resources" check command used
"skip_if" with a lambda. The intention was to only set arguments when
they expanded to a string at least one character in length.
Most deployments configure the variables, i.e.
"openshift_node_cpu_limits_warn", to numbers. Those deployments never
saw limit arguments to "openshift_node_resources" applied.
The "macro" function does not automatically convert values to strings.
Instead the Icinga2 script language returns them in their original type
if and only if they're the only expanded macro ("macro("$foo$=$bar$")"
produces a string with "foo" and "bar" expanded, "macro("$num$")"'s
return type depends on the expanded variable).
The global "len" function is not recommended and the Icinga2
documentation[1] advises to use …
> Replace lambdas with direct runtime macro access

- debian/changelog
- openshift.conf
- redhat/nagios-plugins-openshift.spec
Commit d9f280e fixed a bug due to which "openshift_node_resources"
arguments with numeric values would be silently skipped. As part of that
change the templates for passing selectors to commands,
"openshift-arg-selector" and "openshift-arg-selector-py", were also
changed to use "set_if = "$…$"" rather than calling "len(macro(…))".
Unfortunately that change brought about another issue: "set_if" requires
its value to be either the string "true" or "false", or a value that can
be converted to an integral number. An argument is then only used when
the number is not zero. In the case of "openshift_node_resources" that
was the case as the variables are numbers.
Selectors are usually of the form "label=value". Checks using the
selector templates would have the selector silently dropped. Icinga …
> Re-introduce lambdas for "set_if"

- check_openshift_node_log_heartbeat
- debian/changelog
- redhat/nagios-plugins-openshift.spec
In OpenShift Origin 3.9 the field "systemd.u.SYSLOG_IDENTIFIER" is
analyzed and can't be matched for exact equality. Instead the "match"
filter must be used.
> node_log_heartbeat: Make query work with OpenShift Origin 3.9

- check_openshift_pod_node_alloc
Ever since its initial implementation the "pod_node_alloc" plugin would
report a critical state if two or more pods with a given selectors were
allocated to the same node. With larger deployments, i.e. 5 pods, that
is usually acceptable. Even with deployments as small as three replicas
two instances on a single node are acceptable.
With this change the decision logic is changed to only complain if
either >50% or >3 of pods are on a single node. This way three-replica
deployments are considered okay if they have two pods on a single node.
> Relax check for pod-to-node allocation

- check_openshift_pv_avail
Persistent volume objects without a storage class name aren't
necessarily in the default storage class. Name them for what they are.
> pv_avail: Replace "default class" with "without storage class"

- check_openshift_object_stats
- check_openshift_project_pod_phase
- debian/changelog
- openshift.conf
- redhat/nagios-plugins-openshift.spec
The new plugin, "check_openshift_object_stats", is derived from
"check_openshift_project_pod_phase". The latter will be removed in
a future version as the new plugin contains all of its functionality.
Unlike its predecessor "check_openshift_object_stats" uses a far more
generic algorithm implemented in jq. Limits can be applied via
plain-text metric names or via regular expressions. Along with pod
statistics, global and per namespace and pod phase, cron job statistics
are also computed. Other types will be easy to add.
> Add plugin to observe pod, cronjob statistics

- check_openshift_object_stats
- debian/changelog
- debian/files
- openshift.conf
- redhat/nagios-plugins-openshift.spec
In commit 64c81d7 a new plugin, "check_openshift_object_stats" was
added. It would compute statistics over objects from all namespaces.
There are cases where that's undesired, hence this change adds an
optional parameter to specify the namespace.
> object_stats: Allow restricting namespace

- check_openshift_object_stats
- debian/changelog
- redhat/nagios-plugins-openshift.spec
The "check_openshift_object_stats" script can generate very large
numbers of performance metrics, leading Icinga to truncate the list.
With this change only metrics with defined limits or an unhealthy status
are output. In verbose mode all metrics are output.
> object_stats: Output only metrics with limits by default

- check_openshift_object_stats
- debian/changelog
- redhat/nagios-plugins-openshift.spec
When there are no metrics to report the exit status was "unknown". That
could be confusing.
> object_stats: Return OK without metrics

- check_openshift_es_stats
- debian/changelog
- redhat/nagios-plugins-openshift.spec
Since at least early 2018 OpenShift has used the deployment
configuration's name with its random suffix as the name for each
Elasticsearch instance. At the time of commit c04a18c that wasn't the
case yet. Unlike the "host" key, an IP address, the deployment
configuration name can easily be identified in a list of objects.
At the same time the functionality to strip prefixes from names is
amended with the ability to specify multiple and the default list is
extended to include "logging-es-data-master-".
> es_stats: Use Elasticsearch instance name in metrics

- Makefile
- redhat/nagios-plugins-openshift.spec
The "python3-nagiosplugin" package is built against Python 3.4. With the
default Python version on CentOS/RHEL having become 3.6 recently we need
to change the code to explicitly use the Python 3.4 interpreter. This
was already reflected in the package dependencies.
> Explicitly use Python 3.4 on CentOS/RHEL

- check_openshift_es_stats
- debian/changelog
- openshift.conf
- redhat/nagios-plugins-openshift.spec
The "check_openshift_es_stats" would only generate per-node metrics and
apply limits to those. With this change the computation of the per-node
limits is unified with shared code and that is then used as a basis to
also compute cluster-wide statistics, allowing for limits to be applied
to alert on, for example, "more than 80% of disk space across all nodes
is used".
> es_stats: Compute global statistics

- check_openshift_object_stats
- debian/changelog
- redhat/nagios-plugins-openshift.spec
Pods stuck in a terminal state would usually only be noticed by
a person. With this change a new metric is emitted when any of the
objects encountered by "check_openshift_object_stats" has a deletion
timestamp, defined by the API as "time when object is no longer expected
to exist", that is after the grace period.
> object_stats: Emit deletion timestamps as metric

- check_openshift_object_stats
The Kubernetes job controller will only set the completion time on a Job
when the job's succeeded count is >= the Job's `.spec.completions` field
if the field is set, or 1 otherwise.  The controller will retry the job
unless the retries have exceeded `.spec.backoffLimit`.
Therefore a Job can have a failed count of > 0 and a succeeded count of > 0
while still counting as successful, contrary to the previous
implementation of the object_stats check.
This commit removes the condition of requiring a failed count == 0 to
treat a Job execution as successful, as the presence of a completion
timestamp in conjunction with no active jobs and > 0 completed jobs is
sufficient to determine that a Job completed successfully, see the Job
controller implementation [1].
[1] …
> Ignore failed count when determining whether Job succeeded

- debian/changelog
- new-app-and-wait
- redhat/nagios-plugins-openshift.spec
The creation of the builder service account token is delayed
on HA master environments. This causes rarely the situation
a build is started without an accessible access token and
stick in the state new. To reduce the chance to get into
this situation, a sleep of 3 seconds is added between
creating the project and starting the build.
For more information about this known bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1719792
> new-app-and-wait: Add workaround token generation delayed

- check_openshift_pv_avail
Add option to check_openshift_pv_avail for ignoring entiry storage classes.
> check_openshift_pv_avail: add option to ignore entire storageclasses
